#!/usr/bin/bash
#restore file from ~/recycle
read -p "What file do you want to restore: " fname
[ -f ~/recycle/$fname ]

stat=$?

if [ $stat -eq "0" ];then
mv -i ~/recycle/$fname .;else
echo "file does not exist"
fi

#if [ $stat -ne "0" ]; then
#echo "File does not exist"
#fi

echo ""
echo "complete"
