#!/usr/bin/bash
# search script
# 1) Create a search script
# 2) prompt for file name
# 3) get rid of errors
# 4) display results on screen

echo " Search script is starting"
echo ""

# get user input for file name
read -p "What is the file name you want to search for: " FILENAME

# search for file
LOCATION=`find ~ -name $FILENAME`

# check if successfull
test -f $LOCATION

if [ -e $LOCATION ]
then
	echo "$FILENAME found in: $LOCATION"
#else
#	echo "$FILENAME was not found"
fi
if [ !-e $LOCATION ]
then
	echo "No file found"
fi
# finish
echo ""
echo "Search script is complete"
